// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xafdfqwzoirujtlfxpaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZmRmcXd6b2lydWp0bGZ4cGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMjg0MTUsImV4cCI6MjA4ODgwNDQxNX0.JMYmeyGC-bIwJZF_xx1g4SHNFBomM0ehYi0VPhUiBYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});